
export const emojiMap: { [key: string]: any } = {
  ":angryold:": require("../assets/emoticons/angryold.png"),
  ":annoyedold:": require("../assets/emoticons/annoyedold.png"),
  ":bum:": require("../assets/emoticons/bum.png"),
  ":callme:": require("../assets/emoticons/callme.png"),
  ":cheekyold:": require("../assets/emoticons/cheekyold.png"),
  ":confused:": require("../assets/emoticons/confused.png"),
  ":coolold:": require("../assets/emoticons/coolold.png"),
  ":cry:": require("../assets/emoticons/cry.png"),
  ":curiousold:": require("../assets/emoticons/curiousold.png"),
  ":dies:": require("../assets/emoticons/dies.png"),
  ":disgustold:": require("../assets/emoticons/disgustold.png"),
  ":dizzy:": require("../assets/emoticons/dizzy.png"),
  ":drooling:": require("../assets/emoticons/drooling.png"),
  ":flirt:": require("../assets/emoticons/flirt.png"),
  ":football:": require("../assets/emoticons/football.png"),
  ":goal:": require("../assets/emoticons/goal.png"),
  ":happy:": require("../assets/emoticons/happy.png"),
  ":hugme:": require("../assets/emoticons/hugme.png"),
  ":hugme2:": require("../assets/emoticons/hugme2.png"),
  ":hypnotized:": require("../assets/emoticons/hypnotized.png"),
  ":insane:": require("../assets/emoticons/insane.png"),
  ":kissback:": require("../assets/emoticons/kissback.png"),
  ":kisslips:": require("../assets/emoticons/kisslips.png"),
  ":kissme:": require("../assets/emoticons/kissme.png"),
  ":kissold:": require("../assets/emoticons/kissold.png"),
  ":love:": require("../assets/emoticons/love.png"),
  ":nerd:": require("../assets/emoticons/nerd.png"),
  ":sad:": require("../assets/emoticons/sad.png"),
  ":shocked:": require("../assets/emoticons/shocked.png"),
  ":shy:": require("../assets/emoticons/shy.png"),
  ":shyold:": require("../assets/emoticons/shyold.png"),
  ":silent:": require("../assets/emoticons/silent.png"),
  ":sleeping:": require("../assets/emoticons/sleeping.png"),
  ":sleepy:": require("../assets/emoticons/sleepy.png"),
  ":ssh:": require("../assets/emoticons/ssh.png"),
  ":unimpressed:": require("../assets/emoticons/unimpressed.png"),
  ":wink:": require("../assets/emoticons/wink.png"),
  ":yuck:": require("../assets/emoticons/yuck.png"),
  ":yum:": require("../assets/emoticons/yum.png"),
  ":err:": require("../assets/emoticons/err.png"),
  ":speechless:": require("../assets/emoticons/speechless.png"),
  ":veryhappy:": require("../assets/emoticons/veryhappy.png"),
};

export const emojiList = Object.keys(emojiMap).map((key) => ({
  code: key,
  image: emojiMap[key],
}));
